version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adocs-api
    ports:
      - '8000:8000'
    volumes:
      # Mount for hot reload during development
      - ./main.py:/app/main.py
      - ./BE:/app/BE
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - adocs-network

networks:
  adocs-network:
    driver: bridge
